.TH "E:/Users/1/Desktop/Anton_cpp/server-main Directory Reference" 3 "RudkevichAntonGerasimovich" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Users/1/Desktop/Anton_cpp/server-main Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmdfile\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmdfile\&.h\fP"
.br
.ti -1c
.RI "file \fBserver\&.cpp\fP"
.br
.ti -1c
.RI "file \fBUnitTest\&.cpp\fP"
.br
.in -1c
