.TH "E:/Users/1/Desktop/Anton_cpp/server-main/main.cpp" 3 "RudkevichAntonGerasimovich" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Users/1/Desktop/Anton_cpp/server-main/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mdfile\&.h'\fP
.br
\fC#include <cfloat>\fP
.br
\fC#include <iomanip>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.RI "main file Rudkevich Anton Gerasimovich Server avaluate sum of squares\&. Overflow protection exist\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
main file Rudkevich Anton Gerasimovich Server avaluate sum of squares\&. Overflow protection exist\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for RudkevichAntonGerasimovich from the source code\&.
