.TH "server" 3 "RudkevichAntonGerasimovich" \" -*- nroff -*-
.ad l
.nh
.SH NAME
server \- main file Rudkevich Anton Gerasimovich contain class server  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBserver\fP (int vport, std::string verror, std::string vfile_error, std::string vfile_name)"
.br
.ti -1c
.RI "int \fBexchange\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBport\fP"
.br
.ti -1c
.RI "std::string \fBerror\fP"
.br
.ti -1c
.RI "std::string \fBfile_error\fP"
.br
.ti -1c
.RI "std::string \fBfile_name\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
main file Rudkevich Anton Gerasimovich contain class server 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "server::server (int vport, std::string verror, std::string vfile_error, std::string vfile_name)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int server::exchange ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string server::error"

.SS "std::string server::file_error"

.SS "std::string server::file_name"

.SS "int server::port"


.SH "Author"
.PP 
Generated automatically by Doxygen for RudkevichAntonGerasimovich from the source code\&.
