.TH "C:/Users/kruva/Downloads/server-main/main.cpp" 3 "RudkevichAnton" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/kruva/Downloads/server-main/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mdfile\&.h'\fP
.br
\fC#include <cfloat>\fP
.br
\fC#include <iomanip>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.RI "Главный файл курсовой работы Рудкевич Антона Максимовича @detailed \fBmain\&.cpp\fP - Главный файл Сервер: вычисляет сумму квадратов и возвращает клиенту Есть защита от переполнения типа double\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Главный файл курсовой работы Рудкевич Антона Максимовича @detailed \fBmain\&.cpp\fP - Главный файл Сервер: вычисляет сумму квадратов и возвращает клиенту Есть защита от переполнения типа double\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for RudkevichAnton from the source code\&.
