.TH "C:/Users/kruva/Downloads/server-main/mdfile.cpp" 3 "RudkevichAnton" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/kruva/Downloads/server-main/mdfile.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mdfile\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBMD\fP (std::string sah)"
.br
.RI "Обертка для функций хеширования и ошибок "
.ti -1c
.RI "void \fBerrors\fP (std::string error, std::string name)"
.br
.ti -1c
.RI "int \fBer\fP (std::string file_name, std::string file_error)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int er (std::string file_name, std::string file_error)"

.SS "void errors (std::string error, std::string name)"

.SS "std::string MD (std::string sah)"

.PP
Обертка для функций хеширования и ошибок 
.SH "Author"
.PP 
Generated automatically by Doxygen for RudkevichAnton from the source code\&.
