.TH "C:/Users/kruva/Downloads/server-main/UnitTest.cpp" 3 "RudkevichAnton" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/kruva/Downloads/server-main/UnitTest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mdfile\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest\fP ()"
.br
.RI "Тест файлов базы и ошибок "
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SS "void test ()"

.PP
Тест файлов базы и ошибок 
.SH "Author"
.PP 
Generated automatically by Doxygen for RudkevichAnton from the source code\&.
